name: Deploy single
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
     - run: docker build -t single ./frontend && docker tag single:latest mevanmanilka/single:latest && docker push mevanmanilka/single:latest
     - run: docker build -t cygnetops/react-test -f ./frontend/Dockerfile.dev ./frontend
     - run: docker run -e CI=true cygnetops/react-test npm test
     - name: Generate deployment package
       run: cd frontend && zip -r ../deployment-package.zip . -x '*.git*'

     - name: Upload to EB
       uses: einaregilsson/beanstalk-deploy@v20
       with:
         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         application_name: "single"
         environment_name: "Single-env"
         existing_bucket_name: "elasticbeanstalk-us-east-1-724084651959"
         region: "us-east-1"
         version_label: "v-${{ github.run_number }}"
         deployment_package: "deployment-package.zip"
